heading_control:
  omega: 1.5
  zeta: 1.0
  ki_scale: 5
  ki_saturation_limit: 15  #degrees
  N_rr: 25
  linearization_point: 0.2
  
speed_control:
  K_p: 1
  ki_scale: 5
  ki_saturation_limit: 1.25  #m/s
  X_uu: 100